/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../public/models/bmw_m4_widebody.glb --transform 
Files: ../../../public/models/bmw_m4_widebody.glb [22.52MB] > E:\cars-landing-page\src\components\3d\bmw_m4_widebody-transformed.glb [2.39MB] (89%)
Author: vecarz (https://sketchfab.com/heynic)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/bmw-m4-widebody-wwwvecarzcom-a5687befab084efdba9a5c99a9a8ad4c
Title: BMW M4 Widebody | www.vecarz.com
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/bmw_m4_widebody-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_8.geometry} position={[0, 0.424, 0]}>
        <meshPhysicalMaterial
          {...materials.PaletteMaterial001}
          clearcoat={1}
          clearcoatRoughness={0.05}
          roughness={0.15}
          metalness={0.9}
        />
      </mesh>
      <mesh geometry={nodes.Object_14.geometry} material={materials.PaletteMaterial002} position={[0, 0.424, 0]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.bBMW_M4CompetitionG82TNR0_2021EngineA_Material1} position={[0, 0.444, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.bBMW_M4CompetitionG82TNR0_2021Coloured_Material_004} position={[0, 0.444, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.bBMW_M4CompetitionG82TNR0_2021Carbon1_Material1} position={[0, 0.444, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha5A_Material1} position={[0, 0.444, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha9A_Material1} position={[0, 0.444, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.bBMW_M4CompetitionG82TNR0_2021InteriorA_Material1} position={[0, 0.444, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.phong2} position={[0, 0.444, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_67.geometry} material={materials.bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha6A_Material1} position={[0, 0.446, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha7A_Material1} position={[0, 0.446, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.bBMW_M4CompetitionG82TNR0_2021GrilleNoAlpha8A_Material1} position={[0, 0.446, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.bBMW_M4CompetitionG82TNR0_2021BadgeA_Material1} position={[0, 0.446, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_79.geometry} material={materials.PaletteMaterial003} position={[0, 0.446, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_85.geometry} position={[0, 0.446, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822}>
        <meshStandardMaterial {...materials.bBMW_M4CompetitionG82TNR0_2021LightA_Material1} emissive="#ffffff" emissiveIntensity={12} />
      </mesh>
      <mesh geometry={nodes.Object_88.geometry} material={materials.bBMW_M4CompetitionG82TNR0_2021ManufacturerPlateA_Material1} position={[0, 0.446, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_93.geometry} material={materials.PaletteMaterial004} position={[0, 0.446, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.PaletteMaterial005} position={[0, 0.446, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.PaletteMaterial006} position={[0, 0.446, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.822} />
      <mesh geometry={nodes.Object_118.geometry} material={materials.PaletteMaterial007} position={[0, 0.172, 0]} />
      <mesh geometry={nodes.Object_121.geometry} material={materials.PaletteMaterial008} position={[0, 0.172, 0]} />
      <mesh geometry={nodes.Object_124.geometry} material={materials.PaletteMaterial009} position={[0, 0.172, 0]} />
      <mesh geometry={nodes.Object_142.geometry} material={materials.PaletteMaterial010} rotation={[2.558, 0, Math.PI]} scale={0.553} />
      <mesh geometry={nodes.Object_145.geometry} material={materials.PaletteMaterial011} />
      <mesh geometry={nodes.Object_176.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/models/bmw_m4_widebody-transformed.glb')
