/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../public/models/mclaren_w1.glb --transform 
Files: ../../../public/models/mclaren_w1.glb [47.4MB] > E:\cars-landing-page\src\components\3d\mclaren_w1-transformed.glb [5.28MB] (89%)
Author: GhostMesh (https://sketchfab.com/GhostMesh)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-w1-bd9f427a70f849a0add3bdb618221cab
Title: Mclaren W1
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/mclaren_w1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.INT_DECAL_WHITE} position={[0, 0.438, 0.379]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.EXT_EMISSIVE} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.INT_plastic_red} position={[0, 0.333, 0.089]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.EXT_BLACK_GLASS} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.EXT_EMISSIVE_NM} position={[0, 1.044, 1.313]} rotation={[-Math.PI / 2, 0, 0]} scale={0.026} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.EXT_BLACK_MISC} position={[0, 1.044, 1.313]} rotation={[-Math.PI / 2, 0, 0]} scale={0.026} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.EXT_GLASS_RED} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.EXT_GLASS} position={[0, 1.044, 1.313]} rotation={[-Math.PI / 2, 0, 0]} scale={0.026} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.MIRROR_PLACEMENT} position={[0, 1.044, 1.313]} rotation={[-Math.PI / 2, 0, 0]} scale={0.026} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.INT_GAUGE_GLASS} position={[0, 0.394, 0.292]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.EXT_INTERCOOLER} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.EXT_EXHAUST_TITANIUM} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.EXT_WINDOW} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.INT_WINDOW} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.EXT_REFLECTOR} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.EXT_disc} position={[0.809, 0.349, -1.498]} rotation={[0, 0, 0.009]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.ext_Wheel_brake_caliper} position={[0.825, 0.35, 1.172]} rotation={[-1.571, 1.553, -3.14]} scale={1.199} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.EXT_underside} position={[0.778, 0.348, 1.172]} rotation={[0, 0, 0.035]} />
      <mesh geometry={nodes.Object_81.geometry} material={materials.EXT_CHROME} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_83.geometry} material={materials.EXT_CHROME_BLACK} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_89.geometry} material={materials.EXT_PLASTIC} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_93.geometry} material={materials.EXT_PLASTIC_GLOSS} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_97.geometry} material={materials.EXT_CARBON} position={[0, 1.044, 1.313]} rotation={[-Math.PI / 2, 0, 0]} scale={0.026} />
      <mesh geometry={nodes.Object_101.geometry} material={materials.ext_Body_Paint} position={[0, 1.044, 1.313]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_111.geometry} material={materials.ext_Wheel_paint1} position={[0.915, 0.352, 1.172]} rotation={[-1.571, 1.536, 1.571]} />
      <mesh geometry={nodes.Object_113.geometry} material={materials.EXT_RIM_PLASTIC_GLOSS} position={[0.915, 0.352, 1.172]} rotation={[-1.571, 1.536, 1.571]} />
      <mesh geometry={nodes.Object_115.geometry} material={materials.EXT_RIM_CHROME} position={[0.915, 0.352, 1.172]} rotation={[-1.571, 1.536, 1.571]} />
      <mesh geometry={nodes.Object_117.geometry} material={materials.WHEEL} position={[0.84, 0.349, 1.172]} rotation={[-Math.PI / 2, -0.035, 0]} scale={0.945} />
      <mesh geometry={nodes.Object_149.geometry} material={materials.int_aluminium} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_152.geometry} material={materials.INT_PLASTIC_GLOSS} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.INT_CHROME_BLUE} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_158.geometry} material={materials.INT_CLUSTER} position={[0, 1.012, 0.247]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_168.geometry} material={materials.BLACKMISC} position={[0.297, 0.764, 0.588]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_170.geometry} material={materials.INT_CARBON_AO} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_176.geometry} material={materials.int_leather_paint1} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_178.geometry} material={materials.int_leather_paint3} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_180.geometry} material={materials.INT_PLASTIC} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_192.geometry} material={materials.INT_CHROME_RED} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_201.geometry} material={materials.int_leather_paint2} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_207.geometry} material={materials.int_light_paint1} position={[0.297, 0.86, 0.754]} />
      <mesh geometry={nodes.Object_276.geometry} material={materials.INT_ARROW} position={[0.438, 0.803, 0.59]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Object_287.geometry} material={materials['Material.001']} position={[0.495, 0.591, 0.581]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/mclaren_w1-transformed.glb')
