/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../public/models/mclaren_f1_gtr_longtail.glb --transform 
Files: ../../../public/models/mclaren_f1_gtr_longtail.glb [16.04MB] > E:\cars-landing-page\src\components\3d\mclaren_f1_gtr_longtail-transformed.glb [1.31MB] (92%)
Author: vecarz (https://sketchfab.com/heynic)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-f1-gtr-longtail-wwwvecarzcom-a6dbc062d2e843828c392bbd07727ead
Title: McLaren F1 GTR Longtail | www.vecarz.com
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/mclaren_f1_gtr_longtail-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_8.geometry} material={materials.mclaren_f1gtr_paint} scale={9.344} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.mclaren_f1gtr_paint_carbon_matte} scale={9.344} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.mclaren_f1gtr_windows2} scale={9.344} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.mclaren_f1gtr_windows} scale={9.344} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.generic_carbon_matte_2} scale={9.344} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.mclaren_f1gtr_misc} scale={9.344} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.mclaren_f1gtr_badges} scale={9.344} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.lightB} scale={9.344} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.lightBSmall} scale={9.344} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.lightBackColor} scale={9.344} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.generic_carbon} scale={9.344} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.mclaren_f1gtr_disc} position={[7.554, 2.896, 12.726]} scale={9.344} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.mclaren_f1gtr_lights} scale={9.344} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.lightHead} scale={9.344} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.mclaren_f1gtr_taillight} scale={9.344} />
      <mesh geometry={nodes.Object_89.geometry} material={materials.mclaren_f1gtr_interior} scale={9.344} />
      <mesh geometry={nodes.Object_95.geometry} material={materials.generic_tread} position={[7.554, 2.896, 12.726]} scale={9.344} />
      <mesh geometry={nodes.Object_97.geometry} material={materials.generic_tyre} position={[7.554, 2.896, 12.726]} scale={9.344} />
      <mesh geometry={nodes.Object_115.geometry} material={materials.mclaren_f1gtr_wheel} position={[7.554, 2.896, 12.726]} scale={9.344} />
      <mesh geometry={nodes.Object_144.geometry} material={materials.mclaren_f1gtr_misc_skin} scale={9.344} />
    </group>
  )
}

useGLTF.preload('/models/mclaren_f1_gtr_longtail-transformed.glb')
