/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mclaren_gt3.glb --transform 
Files: public/models/mclaren_gt3.glb [35.53MB] > E:\cars-landing-page\mclaren_gt3-transformed.glb [4.11MB] (88%)
Author: toddeppe (https://sketchfab.com/toddeppe)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-gt3-de76e210eb574320997ba4b35e69e16e
Title: McLaren GT3
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/mclaren_gt3-transformed.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.ENGINE} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.CHASSIS} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.INTERIOR} />
      <mesh geometry={nodes.Object_129.geometry} material={materials.GLASS} />
      <mesh geometry={nodes.Object_150.geometry} material={materials.BODY} />
      <mesh geometry={nodes.Object_188.geometry} material={materials.TIRE} />
      <mesh geometry={nodes.Object_200.geometry} material={materials.WHEELFRONT} />
      <mesh geometry={nodes.Object_219.geometry} material={materials.WHEELREAR} />
    </group>
  )
}

useGLTF.preload('/models/mclaren_gt3-transformed.glb')
